apiVersion: apps/v1
kind: Deployment
metadata:
  name: user01-customer-01
  labels:
    app: user01-customer-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user01-customer-01
  template:
    metadata:
      labels:
        app: user01-customer-01
    spec:
      containers:
        - name: user01-customer-01
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user01-customer-01:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PASSWD
              valueFrom:
                secretKeyRef:
                  name: my-password
                  key: password
            - name: DATA1
              valueFrom:
                configMapKeyRef:
                  name: user01-customer-01
                  key: text1
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
